class AddConsumerProfiles < ActiveRecord::Migration
  def change
    create_table :consumer_profiles do |t|
      t.boolean :question1
      t.boolean :question2
      t.boolean :question3
      t.boolean :question4
      t.boolean :question5
      t.boolean :question6
      t.string :box_type
      t.string :sex
      t.boolean :pregnant
      t.string :age_range
      t.date :birthday
      t.string :vegan
      t.string :product_quality
      t.integer :product_type_facial_care
      t.integer :facial_care_oil_balm_cleansers
      t.integer :facial_care_cream_cleansers
      t.integer :facial_care_foaming_cleansers
      t.integer :facial_care_toners
      t.integer :facial_care_daily_moisturizers
      t.integer :facial_care_spf
      t.integer :facial_care_night_moisturizers
      t.integer :facial_care_anti_aging_serums
      t.integer :facial_care_gel_serums
      t.integer :facial_care_eye_creams
      t.integer :facial_care_eye_serums
      t.integer :facial_care_face_decolette_oils_balms
      t.integer :facial_care_blemish_treatments
      t.integer :facial_care_dry_masks
      t.integer :facial_care_wet_masks
      t.integer :facial_care_sheet_masks
      t.integer :facial_care_srubs
      t.integer :facial_care_enzymes
      t.integer :facial_care_peels
      t.integer :facial_care_acids
      t.integer :facial_care_neck_chest_treatments
      t.integer :facial_care_cleansing_treatments
      t.integer :facial_care_tooth_whiteners
      t.integer :product_type_makeup
      t.integer :makeup_liquid_foundation
      t.integer :makeup_cream_foundation
      t.integer :makeup_powder
      t.integer :makeup_cream_blush
      t.integer :makeup_powder_blush
      t.integer :makeup_gel_blush
      t.integer :makeup_cheek_stain
      t.integer :makeup_cream_foundation
      t.integer :makeup_bb_cc_cream
      t.integer :makeup_liquid_concealer
      t.integer :makeup_cream_concealer
      t.integer :makeup_powder
      t.integer :makeup_mascara
      t.integer :makeup_dry_brow_color
      t.integer :makeup_gel_brow_color
      t.integer :makeup_cream_eyeshadow
      t.integer :makeup_powder_eyeshadow
      t.integer :makeup_pencil_eyeliner
      t.integer :makeup_liquid_eyeliner
      t.integer :makeup_gel_eyeliner
      t.integer :makeup_primer
      t.integer :makeup_lipstick
      t.integer :makeup_lip_stain
      t.integer :makeup_lip_gloss
      t.integer :makeup_lip_liner
      t.integer :makeup_highlighter
      t.integer :makeup_blush
      t.integer :makeup_bronzer
      t.integer :makeup_color_correctors
      t.integer :makeup_contouring
      t.integer :makeup_application_tools
      t.integer :product_type_haircare
      t.integer :haircare_shampoo
      t.integer :haircare_dry_shampoo
      t.integer :haircare_rinse_out_conditioner
      t.integer :haircare_leave_in_conditioner
      t.integer :haircare_masks
      t.integer :haircare_treatments
      t.integer :haircare_styling_aids
      t.integer :haircare_grey_cover
      t.integer :haircare_scalp_treatments
      t.integer :product_type_bath_shower
      t.integer :bath_shower_bath_soaks_oils
      t.integer :bath_shower_aromatherapy
      t.integer :bath_shower_bodywash
      t.integer :bath_shower_body_scrubs
      t.integer :bath_shower_scrubbing_tools
      t.integer :bath_shower_soaps
      t.integer :bath_shower_oils
      t.integer :product_type_body_care
      t.integer :body_care_lotions
      t.integer :body_care_oils
      t.integer :body_care_balms
      t.integer :body_care_treatment_products
      t.integer :body_care_hair_removal
      t.integer :body_care_self_tanner
      t.integer :body_care_spf
      t.integer :body_care_peels
      t.integer :body_care_tools
      t.integer :product_type_fragrances
      t.integer :fragrances_perfumes
      t.integer :fragrances_scented_oils
      t.integer :fragrances_body_sprays
      t.integer :fragrances_ambient_scents
      t.integer :product_type_nail_care
      t.integer :nail_care_color
      t.integer :nail_care_cuticle
      t.integer :nail_care_health
      t.integer :nail_care_polish_remover
      t.integer :nail_care_tools
      t.integer :product_type_beauty_accessories
      t.integer :beauty_accessories_cosmetic_brushes
      t.integer :beauty_accessories_bags
      t.integer :beauty_accessories_sponges
      t.integer :beauty_accessories_facial_cleaning_tools
      t.integer :beauty_accessories_hair_brushes
      t.integer :product_type_sexual_health
      t.integer :sexual_health_condoms
      t.integer :sexual_health_enhancement
      t.integer :product_type_feminine_hygiene
      t.boolean :regular_periods
      t.boolean :peri_menopausal
      t.boolean :menopausal
      t.integer :product_type_general_hygiene
      t.integer :general_hygiene_soap
      t.integer :general_hygiene_lotion_balm
      t.integer :general_hygiene_bug_spray
      t.integer :general_hygiene_deodorant
      t.integer :general_hygiene_oral_care
      t.integer :general_hygiene_cleansing_wipes
      t.integer :general_hygiene_hair_body_wash
      t.integer :general_hygiene_lip_balm
      t.integer :product_type_supplements
      t.integer :supplements_vitamins
      t.integer :supplements_anti_oxidants
      t.integer :supplements_essential_fatty_acids
      t.integer :supplements_herbs
      t.integer :product_type_super_foods_health_beverages
      t.integer :super_foods_health_beverages_smoothie_addatives
      t.integer :super_foods_health_beverages_tea
      t.integer :super_foods_health_beverages_coffee
      t.integer :super_foods_health_beverages_energy_beverages
      t.integer :super_foods_health_beverages_athletic_beverages
      t.integer :product_type_lifestyle
      t.integer :lifestyle_reusables
      t.integer :lifestyle_non_toxic_living_goods
      t.integer :lifestyle_small_fashion_accessories
      t.integer :lifestyle_small_home_accessories
      t.integer :product_type_exercise_movement
      t.integer :exercise_movement_barre
      t.integer :exercise_movement_yoga
      t.integer :exercise_movement_pilates
      t.integer :exercise_movement_running
      t.integer :exercise_movement_dance
      t.integer :exercise_movement_circuit_training
      t.integer :exercise_movement_resistance_training
      t.integer :exercise_movement_hiking
      t.integer :exercise_movement_cycling
      t.integer :exercise_movement_swimming
      t.integer :product_type_natural_medicines
      t.integer :product_type_first_aid
      t.integer :first_aid_wound_care
      t.integer :first_aid_rash_care
      t.integer :first_aid_insect_bite_care
      t.integer :first_aid_anti_fungal
      t.integer :first_aid_irritation
      t.boolean :simple_profile
      t.boolean :has_skin_care_goal_oil
      t.boolean :has_skin_care_goal_dryness
      t.boolean :has_skin_care_goal_oil_dryness
      t.boolean :primary_skin_care_goal_general
      t.boolean :primary_skin_care_goal_redness
      t.boolean :primary_skin_care_goal_anti_aging
      t.boolean :primary_skin_care_goal_break_outs
      t.boolean :secondary_skin_care_goal_general
      t.boolean :secondary_skin_care_goal_redness
      t.boolean :secondary_skin_care_goal_anti_aging
      t.boolean :secondary_skin_care_goal_break_outs
      t.integer :skin_concerns_fine_lines
      t.integer :skin_concerns_firmness
      t.integer :skin_concerns_thinning
      t.integer :skin_concerns_lip_volume
      t.integer :skin_concerns_eyelash_eyebrow
      t.integer :skin_concerns_self_tan
      t.integer :skin_concerns_pigmentation
      t.integer :skin_concerns_capillaries
      t.integer :skin_concerns_circles_puffy
      t.integer :skin_concerns_break_outs
      t.integer :skin_concerns_blackheads
      t.integer :skin_concerns_luminosity_flakey
      t.integer :skin_concerns_irritation
      t.integer :skin_concerns_oil
      t.integer :skin_concerns_dryness
      t.integer :skin_concerns_smooth_hydrate_lips
      t.integer :skin_concerns_acne
      t.integer :skin_concerns_sensitivity_irritation
      t.integer :skin_concerns_eczema
      t.integer :skin_concerns_rosacea
      t.integer :skin_tone
      t.boolean :makeup_minimal
      t.boolean :makeup_classic
      t.boolean :makeup_trendy
      t.boolean :makeup_going_out
      t.boolean :makeup_brights
      t.integer :lips_color_blue_reds
      t.integer :lips_color_orange_reds
      t.integer :lips_color_coral
      t.integer :lips_color_plum
      t.integer :lips_color_dark_pink
      t.integer :lips_color_light_pink
      t.integer :lips_color_nude
      t.integer :lips_color_any
      t.integer :eye_color_blues
      t.integer :eye_color_greens
      t.integer :eye_color_purples
      t.integer :eye_color_brown_beige
      t.integer :eye_color_metallics
      t.integer :eye_color_any
      t.integer :nail_color_red
      t.integer :nail_color_pink
      t.integer :nail_color_purple
      t.integer :nail_color_grey
      t.integer :nail_color_metallic
      t.integer :eyebrow_color_light_brown
      t.integer :eyebrow_color_medium_brown
      t.integer :eyebrow_color_dark_brown
      t.integer :eyebrow_color_auburn
      t.integer :eyebrow_color_black
      t.integer :eyebrow_color_any
      t.integer :eyelash_color_brown
      t.integer :eyelash_color_black
      t.integer :eyelash_color_colors
      t.integer :eyelash_color_any
      t.integer :lips_shimmer
      t.integer :cheeks_shimmer
      t.integer :nails_shimmer
      t.integer :eyes_shimmer
      t.integer :face_shimmer
      t.boolean :has_normal_hair
      t.boolean :has_oily_hair
      t.boolean :has_dry_hair
      t.boolean :has_thick_hair
      t.boolean :has_medium_hair
      t.boolean :has_fine_hair
      t.boolean :has_straight_hair
      t.boolean :has_curly_hair
      t.boolean :has_wavy_hair
      t.boolean :has_light_blonde_hair
      t.boolean :has_strawberry_blonde_hair
      t.boolean :has_dark_blonde_hair
      t.boolean :has_medium_brown_hair
      t.boolean :has_dark_brown_hair
      t.boolean :has_ginger_hair
      t.boolean :has_auburn_hair
      t.boolean :has_black_hair
      t.boolean :has_grey_hair
      t.integer :shape_define_curly_hair
      t.integer :maximize_curly_hair
      t.integer :smooth_reduce_curly_hair
      t.integer :detangle_hair
      t.integer :increase_volume_hair
      t.integer :reduce_frizy_hair
      t.integer :repair_damaged_hair
      t.integer :manage_excess_oily_hair
      t.integer :reduce_hair_loss
      t.integer :sooth_flakey_scalp_hair
      t.integer :cover_grey_hair
      t.integer :color_hair
      t.integer :protect_hair_from_heat
      t.integer :sweet_fragrances
      t.integer :fruity_fragrances
      t.integer :citrus_fragrances
      t.integer :classic_floral_fragrances
      t.integer :tropical_floral_fragrances
      t.integer :earthy_fragrances
      t.integer :woodsy_fragrances
      t.integer :herbal_fragrances
      t.integer :musky_fragrances
      t.integer :spicy_fragrances
      t.integer :body_concerns_firming
      t.integer :body_concerns_dry_skin
      t.integer :body_concerns_break_outs
      t.integer :body_concerns_aging_hands
      t.integer :body_concerns_dry_hands
      t.integer :body_concerns_rough_feet
      t.integer :body_concerns_callouses
      t.integer :body_concerns_pilaris_keratosis
      t.integer :health_concern_energy
      t.integer :health_concern_immunity_viral_bacterial
      t.integer :health_concern_anti_oxidant_systemic
      t.integer :health_concern_sports_preformance
      t.integer :health_concern_sports_injury
      t.integer :health_concern_muscle_tightness_pain
      t.integer :health_concern_joint_support
      t.integer :health_concern_systematic_inflammation
      t.integer :health_concern_menstruation
      t.integer :health_concern_conception
      t.integer :health_concern_pregnancy
      t.integer :health_concern_menopause
      t.integer :health_concern_headache
      t.integer :health_concern_seasonal_allergies
      t.boolean :is_dietary_restricted_no_gluten
      t.boolean :is_dietary_restricted_soy_free
      t.boolean :is_dietary_restricted_dairy_free
      t.boolean :is_dietary_restricted_no_eggs
      t.boolean :is_dietary_restricted_no_corn
      t.boolean :is_dietary_restricted_no_tree_nuts
      t.boolean :is_dietary_restricted_no_peanuts
      t.boolean :is_dietary_restricted_no_chocolate
      t.boolean :is_dietary_restricted_no_shellfish
      t.integer :health_concern_digestion
      t.integer :health_concern_cardiovascular
      t.integer :health_concern_circulation
      t.integer :health_concern_nutrition
      t.integer :health_concern_bloodsugar
      t.integer :health_concern_weight_loss
      t.integer :health_concern_weight_gain
      t.integer :health_concern_muscle_gain
      t.integer :health_concern_female_hormones
      t.integer :health_concern_male_hormones
      t.integer :health_concern_stress
      t.integer :health_concern_depression
      t.integer :health_concern_anxiety
      t.integer :health_concern_toxins
      t.integer :health_concern_sleep
      t.integer :health_concern_aging
      t.integer :health_concern_hair_health_general
      t.integer :health_concern_hair_health_hair_loss
      t.integer :health_concern_hair_health_flakey_scalp
      t.integer :health_concern_skin_health_general
      t.integer :health_concern_skin_health_breakouts
      t.integer :health_concern_skin_health_rosacea
      t.integer :health_concern_skin_health_eczema
      t.integer :health_concern_skin_health_psoriasis
      t.integer :health_concern_skin_health_dermatitis
      t.integer :health_concern_skin_health_anti_aging
      t.boolean :buy_products_online
      t.boolean :buy_products_health_food_stores
      t.boolean :buy_products_department_stores
      t.boolean :buy_products_boutiques
      t.boolean :buy_products_chain_beauty_stores
      t.integer :buy_high_end_products
      t.integer :buy_aspirational_brands
      t.integer :buy_affordable_priced
      t.integer :buy_budget_products
      t.boolean :hobby_outdoor_activities
      t.boolean :hobby_water_activities
      t.boolean :hobby_fitness_studio
      t.boolean :hobby_dance
      t.boolean :hobby_gym
      t.boolean :hobby_cooking_baking
      t.boolean :hobby_crafting
      t.boolean :hobby_art
      t.boolean :hobby_reading_non_fiction
      t.boolean :hobby_reading_fantasy_scifi
      t.boolean :hobby_reading_mystery_drama
      t.boolean :hobby_reading_romance
      t.boolean :hobby_photography
      t.boolean :hobby_wellnes_enthusiast
      t.boolean :hobby_acting
      t.boolean :hobby_fashion
      t.boolean :hobby_modeling
      t.boolean :hobby_interior_design
      t.boolean :hobby_sustainabliity
      t.integer :feminine_hygiene_tampons
      t.integer :feminine_hygiene_pads
      t.integer :feminine_hygiene_cups
      t.integer :feminine_hygiene_wipes
      t.integer :feminine_hygiene_cleansers
      t.boolean :question7
      t.boolean :has_light_brown_hair
      t.string :skin_type
      t.string :primary_skin_care_goal
      t.string :secondary_skin_care_goal
      t.string :makeup_look
      t.string :hair_type
      t.string :hair_thickness
      t.string :hair_texture
      t.string :hair_color_string
      t.string :facebook
      t.string :instagram
      t.string :pinterest
      t.string :twitter
      t.string :youtube
      t.string :vimeo
      t.string :blog
    end
  end
end
